 # URL to fasta, or link to local version, otherwise download it from NCBI
 # We need a full fasta for silico data to avoid remapping error
fasta = "data/ref/GCA_000001405.15_GRCh38_full_analysis_set.fna"

# Configuration for raw GIAB patients data
[real]
patients = ["HG002"] #["HG001", "HG002", "HG003", "HG004", "HG005", "HG006", "HG007"]
depths = [50] #, 75, 100]
captures = ["agilent"] #, "idt", "truseq"]
sequencers = ["hiseq4000"] #, "novaseq"]

# Insert controls into a single patient BAM or generate in-silico fastq
# Output will be in data/exp_raw
[silico]
# Capture kit name (the BED must be defined in [capture] below)
capture = "agilent-col6a1"
# Generate a fastq fully in silico
fastq = true
# Either an URL or a local link to insert variants in a BAM file
bam = "data/exp_raw/HG002_hiseq4000_agilent-col6a1_50x.bam"
# Required for generating a bam file
# VCF containing clinvar variants. If not set, the VCF will be downloaded from NCBI
clinvar = "data/exp_raw/clinvar_chr21.vcf.gz"
# Number of random clinvar variants to insert into the BAM file. Default is 1000
nb_variants = 2
# URL to fasta, or link to local version, otherwise download it from NCBI
fasta =  "https://github.com/nf-core/test-datasets/blob/sarek3/data/genomics/homo_sapiens/genome/chr21/sequence/genome.fasta"

# Define here the name of alls captures and the bed file
[capture]
# Those values are mandatory for GIAB data (Baid 2020)
idt = "data/capture/idt_capture.grch38.bed"
truseq = "data/capture/truseq-dna-exome-targeted-regions-manifest-v1-2-lifted-grch38.bed"
agilent = "data/capture/agilent.targets.grch38.bed"
# For testing
agilent-col6a1 = "data/capture/agilent-col6a1.targets.grch38.bed"

