fasta = "data/ref/chr21.fna"

[silico]
capture = "agilent-col6a1"
clinvar = "data/exp_raw/clinvar_col6a1.vcf.gz"
nb_variants = 2

[silico.varben]
bam_files = ["data/exp_raw/HG002_hiseq4000_agilent-col6a1_50x.bam"]

[capture]
agilent-col6a1 = "data/capture/agilent-col6a1.targets.grch38.bed"
