fasta = "data/ref/chr21.fna"

[silico]
capture = "agilent-col6a1"
clinvar = "data/exp_raw/clinvar_col6a1.vcf.gz"
nb_variants = 2

[silico.simuscop]
# FASTQ are generated according to a list of pre-built profiles. The profile  contains
# sequencer, capture and depth information.
profiles = ["data/ref/profiles/hiseq4000_agilent-col6a1_50x.profile"]
dbsnp = true

[capture]
agilent-col6a1 = "data/ref/capture/agilent-col6a1.targets.grch38.bed"
