params {
	fasta =  "data/ref/chr21.fna"
	fasta_fai =  "data/ref/chr21.fna.fai"
	intervals = "data/capture/agilent.targets.grch38.chr21.bed"
	tools = "haplotypecaller"
	skip_tools = "baserecalibrator,haplotypecaller_filter"
	wes = true
    genome = null
    igenomes_ignore = true
}

process {
	withName: 'GATK4_CREATESEQUENCEDICTIONARY' { memory = 12.GB }
	withName: 'GATK4_MARKDUPLICATES' { memory = 12.GB }
	withName: 'GATK4_HAPLOTYPECALLER' { memory = 12.GB }
	withName: 'BWAMEM1_MEM|BWAMEM2_MEM' {
	    cpus   = 4
        memory =  12.GB
    }
}
