params {
	fasta =  "data/ref/chr21.fna"
	fasta_fai =  "data/ref/chr21.fna.fai"
	intervals = "data/capture/agilent.targets.grch38.chr21.bed"
	tools = "haplotypecaller"
	skip_tools = "baserecalibrator,haplotypecaller_filter"
	wes = true
    genome = null
    igenomes_ignore = true
}

process {
	// github runner limit
	// withName: 'GATK4_.*|BWA.*|FASTQC|FASTP' {
	// 	memory = 7.GB
	// 	cpus = 2
	// }
	withName: '.*' {
		memory = 7.GB
		cpus = 2
	}
}
